/**
 * ASCII Art 상수들
 */
export const SMILE_ASCII_ART = `
  BRXI+=+;==++=:.+..;=++i+++++iYVIIIt=iIIIiiRWWWWWWWWWWWWWt
  BBBMBBBBBXYYtiii+;,:;+=..,.,,..;,;+=iIYItIt+++;;++===XMMMMMMMMWWMMt
  BMBBBBRRRYtit=+i==:..........::.,,;:=+iit=,:,:==;+==+iBMBBBMMMMMBBi
  BBBBRXXXVYIti;,::;............,....;:;t+,,:;===;;,..,;tRXXRBMMMBRX+
  RRXVVVXYtIIIIt+;,................,.,.=:.:::..::;;:...=+IYVXBMMMBXY+
  Yt++iIVIitttii+i=::;=++==:,............,;:=:;,....,:.,=itIVRBMBRYi;
  +=:;+YYtti++itYt+itYVVVYVVI;,........:,,,.....,,:,....,:iIVBMMBRI=;
  IIIIVVt+==+ttYIIiIYVXXXXVXXVI+=;;:,::++++=:,.....,,:,,..,iVRBMMBVI+
  BBBBXYi+==iiIIIitIYXXRRRXXXXRXXVYYYttIIYVYi=,.....;=+=+;;tXBMMMBRBi
  MMMBVi++iiIYt+iIVXXRBBBBBRBRBRBBBBBRXXXXXXVYi=,.....,,,;:IBBMMMMMMt
  WWWBVYIItYYi++IVXRRRRRBBBBBBBMMMBBBBRBBBXXXXYI+=,,...,..,YBMMMMMMMt
  WWMXXYttIt+=tYXXXBBRRRBBBBBBBBBBBBBBBBRRRXXXVVI+,..:,:,.,IMMMMMMMMt
  WWMXVtIIt++tVXXRBBRBBBBBBBBBBBBBBBBBBRBRXXXXXXXV+...,:,,:+BMMMMMMMY
  WWBYi++iIttYVXXXXXRBBBBBBBBBBBBBBBBBRRRXXXXVVXVYt:......,=VMMMMMMMt
  WWRIiiiitIVXXXXRRRRBRRRRRBMMBBBBBBBBBBRRRRXXXVVVYi,.....==XMMMMMWWt
  WWMiiVYIYVVVVVVVVVVVVVYYVVVRRRBBBBBBBRRRRXXVVVVVVV+,..,,:iRMMMMMWWt
  WWWVititVVVVVVVYVVVXXXVVVYIVXXXVXXVVIIIIYYVVVVVVVVI;....iBMMMMWWWWt
  WMMYYiYYVVVVVYIt=;;,,=IiiItiXBRVYi+tIYVVVVVVYIYVVYY=..:,VMMMMMMMWWt
  WMBIIXVYVVXXXVVVVVVVVVVIIVYtXBBVit+==:;=+iIIYIYYVVVi;++VMMMMMMMMWWt
  MMRVVXVYYVVXXXRXVYYVVYYVVVIIXRRVtVVIIIi+I=;;+tYVVYIi+iiBMMMMMMMMWWt
  MMRRXVVVVVVXXRRBRRXRXXXRXVVVXXXYtIVVYYYVVVVVIYVVYIIIIiVMMMMMMMMWWWt
  MMMXVVVVVVVXXXXRRBBBBBBRXVVVXXVYIIYXXXVIIIIYVRVVYttIItMMMMMMMMMMWWV
  MMMMMXVVVVVVXXXRRBBBBBRXVVVVXXVVIIVXXXXVVVVXXXVYIiIYtYMMMMMMMMMMMWI
  XXBMMMVVVVVVVVVVVVXVVVVVYItYVVVVYtIIYVXRXVVVVVYItttIIXMMMMMMMMMMMMMt
  :iXBBYYVVVVXXVVVVVVVVVVVVItYIYIiitIVVVVVVVVYIIIttVXBMMBBBBBMMMMMMMV
  ...:tRXYVVVVVXVXXXVVVXXXXXXXYYVVYYYYVVVVVVYYIIIIiXMMMMBBBBBBBBBBBBBX
  ....XWBYYVVVVXXXXXVt=:iIYVYVYIYYIYYYYVVVVVVYIItitBBBBRRXXRBBBBBBRRRV
  ..;RWWWXYVVVVXXXXXVXVYtIVVXRXBRVI=,:iVVVVVVVIIiiXBBRXVYYVXBBBBRXVVVY
  YWWWWWMVXVVVVVVXXRRRXXVVVIIti+=++tYVVVVVVVIItiVBBRXVIttYVRBBRVYItIY
  WWWWWWWMVVVVVVVVXRRRBXXXXXVVVVVYYVXVVVVYYYItiYRXXYIi+;=tVRBRVYi++iI
  WWWWWWWWMXVVVVVVXXRRBBBXRXVVVVVVVXXVYYYYYIiiIVYIt+=:..,+YRRXVt=::;t
  WWWWWWWWWWRVVVVVVXXRBRRBBRRXXRXXXVVVIIIIttXBRXVIti+;::=tVRRXVIt+iiI
  WWWWWWWWWWWMRVXVVVVXXXRRBRRBXXXXVVYItttYRWWWWWWMBXYIItYVXRBRXXVVXXV
  WWWWWWWWWWWWWMXVXXVVVXRRBRBRXVVVYYIItVBWWWWWWWWWWWWMRRXXRBRBBRRBBBX
  WWWWWWWWWWWWWWWMRVYVVVVVVXVVVVYIIIIYVMWWWWWWWWWWWWWWWWWMBXXXXXXXRRV
  WWWWWWWWWWWWWWWWWBRVYVYVYYYIIYYYYYYVMWWWWWWWWWWWWWWWWWWWWWBVVYYYYVV
  WWWWWWWWWWWWWWWWWWWMRXVVVVVVVVVVYYXWWWWWWWWWWWWWWWWWWWWWWWWBXVYIIYi
  WWWWWWWWWWWWWWWWWWWWWMRXXVVVYVYYVBWWWWWWWMWWWWWWWWWWWWWWWWWMY+;:,.,
  WWWWWWWWWWWWWWWWWWWWWWWMBXYIIVRBWWWWWWWWWMMWWWWWWWWWMBXVVYt;.......
  WWWWWWWWWWWWWWWWWWWWWWWWWViiiIIMWWWWWWWWWWWWWWMBXYi=:..............
  WWWWWWWWWWWWWWWWWWWWWWWMi,.....:MWWWWWWWWWWWWWWX=,.................
  WWWWWWWWWWWWWWWWWWWWWWW;.......;BWWWWWWWWWWWWWWWWWYi:..............
  WWWWWWWWWWWWWWWWWWWWWWWMI,......RMWWWWWWWWWWWWWWWWWWWX:............
  WWWWWWWWWWWWWWWWWWWWWWWWWMt.....=MWWWWWWWWWWWWWWWWWWWWBi;..........
  WWWWWWWWWWWWWWWWWWWWWMWWWWB....=;YWWWWWWWWWWWWWWWWWWWWWWWV.........
  WWWWWWWWWWWWWWWWWWWWWWWWWWt.,:..;:VWWWWWWWWWWWWWWWWWWWWWWWBi.......
`;

/**
 * 애플리케이션 상수들
 */
export const APP_CONSTANTS = {
  TITLE: "모자람 없어도... 재미는 있으니까...",
  SUBTITLE: "웃으면 너도 아저씨",
  BUTTON_LABELS: {
    GET_JOKE: "개그 감상하기",
    SHOW_ANSWER: "정답 보기",
    LOADING: "로딩 중...",
  },
  ERROR_MESSAGES: {
    NO_DATA: "아재개그 데이터를 불러올 수 없습니다.",
    FETCH_ERROR: "개그를 가져오는 중 오류가 발생했습니다.",
  },
};
