name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "React/package-lock.json"

      - name: Install dependencies (React)
        run: npm ci
        working-directory: React

      - name: Run tests
        run: npm test -- --run
        working-directory: React

      - name: Build (production)
        run: npm run build
        working-directory: React
